sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      npm install coveralls
      cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    fi
